{{- if and (not (lookup "v1" "Secret" .Release.Namespace .Values.appSecretName)) (.Values.githubAppId)}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appSecretName }}
  labels:
    app.kubernetes.io/component: deployment
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
type: Opaque
data:
  {{- $encodedAppId := (required ".Values.githubAppId must be set" .Values.githubAppId) | b64enc | quote }}
  {{- $encodedInstallId := (required ".Values.githubAppInstallId must be set" .Values.githubAppInstallId) | b64enc | quote }}
  {{- $encodedPEM := (required ".Values.githubAppPem must be set" .Values.githubAppPem) | b64enc | quote }}
  {{ .Values.appIdSecretKey }}: {{ $encodedAppId }}
  {{ .Values.appInstallIdSecretKey }}: {{ $encodedInstallId }}
  {{ .Values.appPemSecretKey }}: {{ $encodedPEM }}

{{- else if (lookup "v1" "Secret" .Release.Namespace .Values.appSecretName) }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.appSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appSecretName }}
  labels:
    app.kubernetes.io/component: deployment
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
type: Opaque
data:
  {{ .Values.appIdSecretKey }}: {{ (index $secret "data" .Values.appIdSecretKey) | quote }}
  {{ .Values.appInstallIdSecretKey }}: {{ (index $secret "data" .Values.appInstallIdSecretKey) | quote }}
  {{ .Values.appPemSecretKey }}: {{ (index $secret "data" .Values.appPemSecretKey) | quote }}

{{- end }}
