{{- if and (not (lookup "v1" "Secret" .Release.Namespace .Values.secretName)) (.Values.githubPat) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    app.kubernetes.io/component: deployment
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
type: Opaque
data:
  {{- $encodedPAT := (required ".Values.githubPat must be set" .Values.githubPat) | b64enc | quote }}
  {{ .Values.secretKey }}: {{ $encodedPAT }}

{{- else if (lookup "v1" "Secret" .Release.Namespace .Values.secretName) }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.secretName) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    app.kubernetes.io/component: deployment
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
type: Opaque
data:
  {{ .Values.secretKey }}: {{ (index $secret "data" .Values.secretKey) | quote }}

{{- end }}
